### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by andrewdes**
Cleaned up code and finished removing unnecessary components

### CODE REVIEW

**Comment by Ahmad-Ayyoub** [comment]
Looks fine. Just put back the dependencies for JKD 9 & 10.

**Comment by Ahmad-Ayyoub** [comment]
I also got this error
```
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 125 (Exit value: 125)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by andrewdes** [comment]
@Ahmad-Ayyoub is docker running?

**Comment by Ahmad-Ayyoub** [comment]
Yes

**Comment by Ahmad-Ayyoub** [comment]
I think it is pom.xml problem.

**Comment by Ahmad-Ayyoub** [comment]
Btw change 18.0.0.1 to RELEASE

**Comment by Ahmad-Ayyoub** [comment]
Also when I built the app. I got this:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.eventapp.tests.EventAppTest
Jun 26, 2018 5:02:30 PM org.apache.cxf.jaxrs.utils.JAXRSUtils logMessageHandlerProblem
SEVERE: No message body reader has been found for class javax.json.JsonArray, ContentType: text/html;charset=ISO-8859-1
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.722 sec <<< FAILURE! - in it.io.openliberty.guides.eventapp.tests.EventAppTest
runTestsInOrder(it.io.openliberty.guides.eventapp.tests.EventAppTest)  Time elapsed: 2.721 sec  <<< ERROR!
javax.ws.rs.client.ResponseProcessingException: No message body reader has been found for class javax.json.JsonArray, ContentType: text/html;charset=ISO-8859-1
	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:439)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:390)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:320)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:310)
	at it.io.openliberty.guides.eventapp.tests.EventAppTest.sendForm(EventAppTest.java:86)
	at it.io.openliberty.guides.eventapp.tests.EventAppTest.testCreatingNewEvent(EventAppTest.java:62)
	at it.io.openliberty.guides.eventapp.tests.EventAppTest.runTestsInOrder(EventAppTest.java:57)


Results :

Tests in error:
  EventAppTest.runTestsInOrder:57->testCreatingNewEvent:62->sendForm:86 » ResponseProcessing

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

There is also an issue when you run `mvn clean install` a second time. A maven error shows up relating to docker that there is already a used container call jpa_guide. We should not stop and rm docker everytime we run `mvn clean install`.

**Comment by Ahmad-Ayyoub** [comment]
Looks good.

**Comment by Ahmad-Ayyoub** [comment]
Looks good

**Pull request merged**
